// Centralized fallback text for templates — keyed by businessType.
// When a user picks a template from a different business type,
// these ensure the fallback copy matches their actual business, not the template's original type.

const FALLBACK_MAP = {
  tint_shop: {
    shopName: 'Premium Tint',
    navSubtitle: 'Tint & Protection',
    heroBadge: 'Premium Tint & Film Protection',
    headline: 'Precision Tinting. Premium Results.',
    subheadline: 'Professional window tinting and paint protection film.',
    statLabel: 'Cars Tinted',
    aboutFallback: 'premium window tinting and film protection',
    ctaHeadline: 'Get a Free Quote',
    footerDesc: 'Professional Tinting',
    statLabel2: 'Cars Transformed',
    guaranteeLabel: 'Satisfaction Guaranteed',
    tickerItems: ['Window Tinting', 'Paint Protection Film', 'Ceramic Coating', 'UV Protection'],
    defaultProducts: [
      { name: 'Window Tinting', description: 'Premium film installation', price: '$199+', badge: 'Popular' },
      { name: 'Paint Protection', description: 'Full-body film coverage', price: '$499+' },
      { name: 'Ceramic Coating', description: 'Long-lasting paint protection', price: '$349+' },
    ],
    whyUsTitle: 'Precision Work',
  },
  detailing_shop: {
    shopName: 'Elite Detailing',
    navSubtitle: 'Auto Detailing',
    heroBadge: 'Professional Auto Detailing',
    headline: 'Flawless Detail. Every Time.',
    subheadline: 'Professional auto detailing that exceeds expectations.',
    statLabel: 'Cars Detailed',
    aboutFallback: 'professional auto detailing services',
    ctaHeadline: 'Reserve Your Detail Session',
    footerDesc: 'Professional Vehicle Detailing',
    statLabel2: 'Cars Transformed',
    guaranteeLabel: 'Satisfaction Guaranteed',
    tickerItems: ['Full Detail', 'Ceramic Coating', 'Paint Correction', 'Interior Deep Clean'],
    defaultProducts: [
      { name: 'Full Detail', description: 'Complete interior & exterior', price: '$199+', badge: 'Popular' },
      { name: 'Ceramic Coating', description: 'Long-lasting paint protection', price: '$499+' },
      { name: 'Paint Correction', description: 'Swirl & scratch removal', price: '$349+' },
    ],
    whyUsTitle: 'Professional Results',
  },
  mobile_detailing: {
    shopName: 'Mobile Detail',
    navSubtitle: 'Mobile Detailing',
    heroBadge: 'Professional Mobile Detailing',
    headline: 'Premium Detail. We Come To You.',
    subheadline: 'Professional mobile detailing at your door.',
    statLabel: 'Cars Detailed',
    aboutFallback: 'professional mobile detailing services',
    ctaHeadline: 'Schedule a Mobile Detail',
    footerDesc: 'Mobile Detailing',
    statLabel2: 'Cars Transformed',
    guaranteeLabel: 'Satisfaction Guaranteed',
    tickerItems: ['Full Detail', 'Interior Clean', 'Ceramic Coating', 'Paint Protection'],
    defaultProducts: [
      { name: 'Full Detail', description: 'Complete mobile service', price: '$149+', badge: 'Popular' },
      { name: 'Interior Deep Clean', description: 'Seats, carpets & dash', price: '$99+' },
      { name: 'Ceramic Coating', description: 'Long-lasting protection', price: '$399+' },
    ],
    whyUsTitle: 'We Come To You',
  },
  mechanic_shop: {
    shopName: 'Auto Repair',
    navSubtitle: 'Auto Repair',
    heroBadge: 'Trusted Auto Repair',
    headline: 'Honest Repairs. Expert Service.',
    subheadline: 'Reliable auto repair with honest pricing and expert technicians.',
    statLabel: 'Cars Repaired',
    aboutFallback: 'expert auto repair',
    ctaHeadline: 'Schedule Your Repair',
    footerDesc: 'Auto Repair',
    statLabel2: 'Satisfied Customers',
    guaranteeLabel: 'Guaranteed Work',
    tickerItems: ['Engine Repair', 'Brake Service', 'Oil Change', 'Diagnostics'],
    defaultProducts: [
      { name: 'Engine Repair', description: 'Full diagnostics & repair', price: '$299+', badge: 'Popular' },
      { name: 'Brake Service', description: 'Pads, rotors & fluid', price: '$199+' },
      { name: 'Full Inspection', description: 'Comprehensive vehicle check', price: '$99+' },
    ],
    whyUsTitle: 'Expert Technicians',
  },
  car_wash: {
    shopName: 'Car Wash',
    navSubtitle: 'Car Wash',
    heroBadge: 'Professional Car Wash',
    headline: 'Spotless Clean. Every Visit.',
    subheadline: 'A top-tier car wash experience every time.',
    statLabel: 'Cars Washed',
    aboutFallback: 'a top-tier car wash',
    ctaHeadline: 'Get Washed Today',
    footerDesc: 'Car Wash',
    statLabel2: 'Happy Customers',
    guaranteeLabel: 'Satisfaction Guaranteed',
    tickerItems: ['Express Wash', 'Full Service', 'Interior Clean', 'Wax & Shine'],
    defaultProducts: [
      { name: 'Express Wash', description: 'Quick exterior clean', price: '$15+', badge: 'Popular' },
      { name: 'Full Service', description: 'Interior & exterior', price: '$35+' },
      { name: 'Premium Detail', description: 'The works — inside & out', price: '$79+' },
    ],
    whyUsTitle: 'Spotless Results',
  },
  wheel_shop: {
    shopName: 'Wheel Shop',
    navSubtitle: 'Wheels & Tires',
    heroBadge: 'Custom Wheels & Tires',
    headline: 'Custom Wheels. Perfect Fitment.',
    subheadline: 'Expert wheel and tire services for every ride.',
    statLabel: 'Wheels Installed',
    aboutFallback: 'expert wheel and tire services',
    ctaHeadline: 'Get a Quote',
    footerDesc: 'Wheel & Tire Shop',
    statLabel2: 'Happy Customers',
    guaranteeLabel: 'Fitment Guaranteed',
    tickerItems: ['Custom Wheels', 'Tire Mounting', 'Wheel Balancing', 'Fitment Guaranteed'],
    defaultProducts: [
      { name: 'Custom Wheels', description: '18"–24" alloy wheels', price: '$349+', badge: 'Popular' },
      { name: 'Mount & Balance', description: 'Professional fitment', price: '$89' },
      { name: 'Wheel Repair', description: 'Curb rash & bend fix', price: '$149+' },
    ],
    whyUsTitle: 'Expert Fitment',
  },
};

const GENERIC_FALLBACK = {
  shopName: 'Auto Shop',
  navSubtitle: 'Auto Services',
  heroBadge: 'Professional Auto Services',
  headline: 'Quality Service. Every Time.',
  subheadline: 'Professional automotive services you can trust.',
  statLabel: 'Vehicles Serviced',
  aboutFallback: 'professional automotive services',
  ctaHeadline: 'Get a Free Quote',
  footerDesc: 'Auto Services',
  statLabel2: 'Happy Customers',
  guaranteeLabel: 'Satisfaction Guaranteed',
  tickerItems: ['Professional Service', 'Quality Work', 'Satisfaction Guaranteed', 'Trusted Locally'],
  defaultProducts: [
    { name: 'Service Package', description: 'Our most popular option', price: 'Call', badge: 'Popular' },
    { name: 'Premium Package', description: 'Full-service treatment', price: 'Call' },
    { name: 'Custom Service', description: 'Tailored to your needs', price: 'Call' },
  ],
  whyUsTitle: 'Quality Service',
};

export function getFallbacks(businessType) {
  return FALLBACK_MAP[businessType] || GENERIC_FALLBACK;
}
