// CJS generator
var fs=require("fs");
var NL=String.fromCharCode(10);
var c=[];
var A=function(x){c.push(x);};
A("import React, { useState, useEffect } from 'react';");
A("");
A("export default function DetailingAutoSyncWhite({ businessInfo, generatedCopy, templateMeta }) {");
A("  const c = templateMeta.colors;");
A("  const font = templateMeta.font;");
A("  const bodyFont = templateMeta.bodyFont;");
A("  const [scrolled, setScrolled] = useState(false);");
A("  const [isMobile, setIsMobile] = useState(false);");
A("");
A("  useEffect(() => {");
A("    const link = document.createElement('link');");
A("    link.rel = 'stylesheet';");
A("    link.href = 'https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300&family=DM+Serif+Display:ital@0;1&display=swap';");
A("    document.head.appendChild(link);");
A("    return () => { if (document.head.contains(link)) document.head.removeChild(link); };");
A("  }, []);");
A("");
A("  useEffect(() => {");
A("    const onScroll = () => setScrolled(window.scrollY > 20);");
A("    window.addEventListener('scroll', onScroll);");
A("    return () => window.removeEventListener('scroll', onScroll);");
A("  }, []);");
A("");
A("  useEffect(() => {");
A("    const check = () => setIsMobile(window.innerWidth < 768);");
A("    check();");
A("    window.addEventListener('resize', check);");
A("    return () => window.removeEventListener('resize', check);");
A("  }, []);");
A("");
A("  const white    = c.bg        || '#ffffff';");
A("  const off      = c.secondary || '#f5f5f7';");
A("  const blue     = c.accent    || '#0071E3';");
A("  const text     = c.text      || '#1d1d1f';");
A("  const text2    = '#424245';");
A("  const text3    = c.muted     || '#6e6e73';");
A("  const text4    = '#a1a1a6';");
A("  const border   = 'rgba(0,0,0,0.08)';");
A("  const border2  = 'rgba(0,0,0,0.12)';");
A("  const radius   = '18px';");
A("  const radiusSm = '12px';");
A("  const shadowSm = '0 2px 12px rgba(0,0,0,0.06)';");
A("  const shadowMd = '0 8px 40px rgba(0,0,0,0.10)';");
A("  const dmSans   = \"'DM Sans', \" + (bodyFont || 'sans-serif');");
A("  const dmSerif  = \"'DM Serif Display', \" + (font || 'serif');");
A("");
A("  const services     = (generatedCopy && generatedCopy.servicesSection && generatedCopy.servicesSection.items) ? generatedCopy.servicesSection.items : [];");
A("  const testimonials = (generatedCopy && generatedCopy.testimonialPlaceholders) ? generatedCopy.testimonialPlaceholders : [];");
A("");
A("  const stats = [");
A("    { num: '2K+',  label: 'Vehicles Detailed' },");
A("    { num: businessInfo.yearsInBusiness ? businessInfo.yearsInBusiness + '+' : '8+', label: 'Years Experience' },");
A("    { num: '100%', label: 'Satisfaction Rate' },");
A("    { num: businessInfo.city || 'Local', label: 'Serving You' },");
A("  ];");
A("");
A("  const specialtyItems = Array.isArray(businessInfo.specialties)");
A("    ? businessInfo.specialties");
A("    : businessInfo.specialties ? [businessInfo.specialties] : ['Auto Auction', 'Fleet Programs', 'Aviation Detail'];");
A("");
A("  const brandItems = ['Koch Chemie', 'CARPRO', 'Rupes', \"Meguiar's\", '3M', 'IGL Coatings'];");
A("  const tileIcons  = ['✦', '◈', '⬡', '◉', '✧', '◆', '◎', '⬟'];");
A("");
A("  const s = {");
A("    wrapper: { background: white, color: text, fontFamily: dmSans, WebkitFontSmoothing: 'antialiased', overflowX: 'hidden' },");
A("    nav: {");
A("      position: 'sticky', top: 0, left: 0, right: 0, zIndex: 100, height: '52px',");
A("      display: 'flex', alignItems: 'center', justifyContent: 'space-between',");
A("      padding: isMobile ? '0 20px' : '0 48px',");
A("      background: scrolled ? 'rgba(255,255,255,0.95)' : 'rgba(255,255,255,0.82)',");
A("      backdropFilter: 'saturate(180%) blur(20px)',");
A("      WebkitBackdropFilter: 'saturate(180%) blur(20px)',");
A("      borderBottom: '1px solid ' + (scrolled ? border2 : border),");
A("      transition: 'background 0.3s, border-color 0.3s',");
A("    },");
A("    navLogo: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '17px', fontWeight: 500, color: text, letterSpacing: '-0.3px', fontFamily: dmSans },");
A("    logoRing: { width: '24px', height: '24px', borderRadius: '50%', background: 'linear-gradient(135deg, #1d1d1f 0%, #6e6e73 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },");
A("    logoRingInner: { width: '10px', height: '10px', borderRadius: '50%', border: '1.5px solid rgba(255,255,255,0.7)' },");
A("    navCta: { background: blue, color: white, fontSize: '13px', fontWeight: 500, padding: '8px 20px', borderRadius: '980px', border: 'none', cursor: 'pointer', fontFamily: dmSans, letterSpacing: '-0.1px', display: isMobile ? 'none' : 'block' },");
A("    hero: { paddingTop: '52px', minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', background: white, position: 'relative', overflow: 'hidden' },");
A("    heroGradient: { position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 60% 50% at 50% 0%, ' + blue + '0f 0%, transparent 70%), radial-gradient(ellipse 40% 30% at 80% 80%, ' + blue + '0a 0%, transparent 60%)', pointerEvents: 'none' },");
A("    heroContent: { position: 'relative', zIndex: 2, maxWidth: '760px', padding: isMobile ? '60px 24px 80px' : '0 24px' },");
A("    heroChip: { display: 'inline-flex', alignItems: 'center', gap: '6px', background: off, border: '1px solid ' + border2, padding: '6px 14px', borderRadius: '980px', fontSize: '12px', color: text3, fontWeight: 500, marginBottom: '32px', letterSpacing: '0.1px' },");
A("    heroChipDot: { width: '6px', height: '6px', borderRadius: '50%', background: blue, flexShrink: 0 },");
A("    heroH1: { fontFamily: dmSerif, fontSize: isMobile ? '40px' : 'clamp(48px, 7vw, 86px)', fontWeight: 400, lineHeight: 1.05, letterSpacing: isMobile ? '-0.5px' : '-1.5px', color: text, marginBottom: '24px' },");
A("    heroAccent: { color: blue },");
A("    heroSub: { fontSize: '19px', lineHeight: 1.6, color: text3, maxWidth: '520px', margin: '0 auto 40px', fontWeight: 300 },");
A("    heroActions: { display: 'flex', gap: '12px', justifyContent: 'center', alignItems: 'center', flexWrap: 'wrap' },");
A("    btnBlue: { background: blue, color: white, padding: '15px 36px', borderRadius: '980px', fontSize: '16px', fontWeight: 500, border: 'none', cursor: 'pointer', fontFamily: dmSans, letterSpacing: '-0.2px', boxShadow: '0 4px 20px ' + blue + '4d' },");
A("    btnGhost: { background: 'transparent', color: blue, fontSize: '16px', fontWeight: 500, border: 'none', cursor: 'pointer', padding: '15px 20px', display: 'flex', alignItems: 'center', gap: '4px', fontFamily: dmSans, letterSpacing: '-0.2px' },");
A("    statsBar: { display: 'grid', gridTemplateColumns: isMobile ? '1fr 1fr' : 'repeat(4,1fr)', gap: '1px', background: border, borderTop: '1px solid ' + border, borderBottom: '1px solid ' + border },");
A("    stat: { padding: isMobile ? '28px 16px' : '40px 32px', textAlign: 'center', background: off },");
A("    statNum: { fontFamily: dmSerif, fontSize: isMobile ? '36px' : '52px', fontWeight: 400, lineHeight: 1, color: text, letterSpacing: '-2px', marginBottom: '8px', display: 'block' },");
A("    statLabel: { fontSize: '13px', color: text3, fontWeight: 400, letterSpacing: '-0.1px' },");
A("    sectionWhite: { padding: isMobile ? '80px 24px' : '120px 80px', background: white },");
A("    sectionOff:   { padding: isMobile ? '80px 24px' : '120px 80px', background: off },");
A("    eyebrow: { fontSize: '12px', fontWeight: 500, color: blue, letterSpacing: '0.5px', textTransform: 'uppercase', marginBottom: '16px', display: 'block' },");
A("    sectionTitle: { fontFamily: dmSerif, fontSize: isMobile ? '34px' : 'clamp(34px, 4vw, 54px)', fontWeight: 400, lineHeight: 1.1, letterSpacing: '-1px', color: text, marginBottom: '20px' },");
A("    titleItalicBlue: { fontStyle: 'italic', color: blue },");
A("    bodyText: { fontSize: '17px', color: text3, lineHeight: 1.7, fontWeight: 300, maxWidth: '560px' },");
A("    servicesIntro: { maxWidth: '600px', margin: '0 auto 72px', textAlign: 'center' },");
A("    servicesBento: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)', gap: '16px' },");
A("    tileBase: { background: off, borderRadius: radius, padding: isMobile ? '28px 24px' : '40px 36px', position: 'relative', overflow: 'hidden', border: '1px solid ' + border },");
A("    tileFeatured: { background: text, borderRadius: radius, padding: isMobile ? '28px 24px' : '40px 36px', position: 'relative', overflow: 'hidden', border: 'none', gridColumn: isMobile ? 'span 1' : 'span 2' },");
A("    tileGlow: { position: 'absolute', top: '-40px', right: '-40px', width: '180px', height: '180px', borderRadius: '50%', background: 'radial-gradient(circle, ' + blue + '1f, transparent 70%)', pointerEvents: 'none' },");
A("    tileGlowFeatured: { position: 'absolute', top: '-40px', right: '-40px', width: '180px', height: '180px', borderRadius: '50%', background: 'radial-gradient(circle, ' + blue + '33, transparent 70%)', pointerEvents: 'none' },");
A("    tileBadge: { position: 'absolute', top: '20px', right: '20px', background: blue, color: white, fontSize: '10px', fontWeight: 600, letterSpacing: '0.5px', padding: '4px 10px', borderRadius: '980px', textTransform: 'uppercase' },");
A("    tileIcon: { width: '44px', height: '44px', borderRadius: '10px', background: white, border: '1px solid ' + border, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', marginBottom: '24px', boxShadow: shadowSm },");
A("    tileIconFeatured: { width: '44px', height: '44px', borderRadius: '10px', background: 'rgba(255,255,255,0.12)', border: '1px solid rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', marginBottom: '24px' },");
A("    tileH3:         { fontSize: '20px', fontWeight: 500, letterSpacing: '-0.3px', color: text,  marginBottom: '10px' },");
A("    tileH3Featured: { fontSize: '20px', fontWeight: 500, letterSpacing: '-0.3px', color: white, marginBottom: '10px' },");
A("    tileP:          { fontSize: '14px', color: text3,                    lineHeight: 1.65 },");
A("    tilePFeatured:  { fontSize: '14px', color: 'rgba(255,255,255,0.6)', lineHeight: 1.65 },");
A("    brands: { padding: isMobile ? '48px 24px' : '56px 80px', borderBottom: '1px solid ' + border, borderTop: '1px solid ' + border, textAlign: 'center', background: white },");
A("    brandsEyebrow: { fontSize: '11px', color: text4, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: '32px', display: 'block' },");
A("    brandsRow: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: isMobile ? '24px' : '48px', flexWrap: 'wrap' },");
A("    brand: { fontSize: '15px', fontWeight: 500, color: '#d1d1d6', letterSpacing: '-0.2px' },");
A("    specStrip: { background: off, borderTop: '1px solid ' + border, borderBottom: '1px solid ' + border, padding: isMobile ? '80px 24px' : '80px', display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: isMobile ? '48px' : '80px', alignItems: 'start' },");
A("    specPillsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginTop: '36px' },");
A("    specPill: { background: white, border: '1px solid ' + border, borderRadius: radiusSm, padding: '18px 20px' },");
A("    specPillLabel: { fontSize: '11px', color: text4, fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '4px' },");
A("    specPillVal:   { fontSize: '15px', fontWeight: 500, color: text, letterSpacing: '-0.2px' },");
A("    fleetCard: { background: white, borderRadius: radius, border: '1px solid ' + border, padding: '40px', boxShadow: shadowMd, position: 'relative', overflow: 'hidden', marginBottom: '16px' },");
A("    fleetCardLine: { position: 'absolute', top: 0, left: 0, right: 0, height: '3px', background: 'linear-gradient(90deg, ' + blue + ', #5AC8FA)', borderRadius: radius + ' ' + radius + ' 0 0' },");
A("    fleetCardNum: { fontFamily: dmSerif, fontSize: '80px', color: '#ebebed', lineHeight: 1, position: 'absolute', right: '24px', top: '16px', pointerEvents: 'none' },");
A("    fleetCardH3: { fontSize: '22px', fontWeight: 500, color: text, letterSpacing: '-0.3px', marginBottom: '14px' },");
A("    fleetCardP:  { fontSize: '14px', color: text3, lineHeight: 1.7, marginBottom: '24px' },");
A("    fleetTags:   { display: 'flex', flexWrap: 'wrap', gap: '8px' },");
A("    tag: { background: off, border: '1px solid ' + border, padding: '5px 12px', borderRadius: '980px', fontSize: '12px', color: text2 },");
A("    testiGrid: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3,1fr)', gap: '16px' },");
A("    tcard: { background: white, borderRadius: radius, border: '1px solid ' + border, padding: '36px', boxShadow: shadowSm },");
A("    tcardStars: { color: '#FF9F0A', fontSize: '14px', marginBottom: '16px', letterSpacing: '2px' },");
A("    tcardP:     { fontSize: '15px', color: text2, lineHeight: 1.7, fontWeight: 300, fontStyle: 'italic', marginBottom: '24px' },");
A("    tcardAuthor: { display: 'flex', alignItems: 'center', gap: '12px' },");
A("    tcardAv: { width: '40px', height: '40px', borderRadius: '50%', background: 'linear-gradient(135deg, #ebebed, #e0e0e4)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '14px', fontWeight: 600, color: text3, border: '1.5px solid ' + border2, flexShrink: 0 },");
A("    tcardName: { fontSize: '14px', fontWeight: 500, color: text },");
A("    tcardRole: { fontSize: '12px', color: text4, marginTop: '1px' },");
A("    footer: { background: text, color: 'rgba(255,255,255,0.6)', padding: isMobile ? '60px 24px 28px' : '64px 80px 32px' },");
A("    footerTop: { display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '2fr 1fr 1fr', gap: isMobile ? '32px' : '60px', marginBottom: '56px' },");
A("    footerBrandLogo: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '17px', fontWeight: 500, color: white, marginBottom: '14px', fontFamily: dmSans },");
A("    footerLogoRing: { width: '24px', height: '24px', borderRadius: '50%', background: 'linear-gradient(135deg, #555 0%, #888 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },");
A("    footerBrandP: { fontSize: '13px', lineHeight: 1.7, maxWidth: '260px' },");
A("    footerColH4: { fontSize: '11px', fontWeight: 600, color: white, letterSpacing: '0.5px', textTransform: 'uppercase', marginBottom: '16px' },");
A("    footerColLink: { fontSize: '13px', color: 'rgba(255,255,255,0.5)', textDecoration: 'none', display: 'block', marginBottom: '10px' },");
A("    footerBottom: { borderTop: '1px solid rgba(255,255,255,0.08)', paddingTop: '24px', display: 'flex', justifyContent: isMobile ? 'center' : 'space-between', alignItems: 'center', flexDirection: isMobile ? 'column' : 'row', gap: isMobile ? '12px' : 0, textAlign: isMobile ? 'center' : 'left' },");
A("    footerLoc: { fontSize: '12px', display: 'flex', alignItems: 'center', gap: '6px' },");
A("    footerDot: { width: '6px', height: '6px', borderRadius: '50%', background: blue },");
A("  };");
A("");
A("  return (");
A("    <div style={s.wrapper}>");
A("");
A("      {/* NAV */}");
A("      <nav style={s.nav}>");
A("        <div style={s.navLogo}>");
A("          <div style={s.logoRing}><div style={s.logoRingInner} /></div>");
A("          {businessInfo.businessName}");
A("        </div>");
A("        <button style={s.navCta}>{generatedCopy.ctaPrimary || 'Book a Detail'}</button>");
A("      </nav>");
A("");
A("      {/* HERO */}");
A("      <section style={s.hero}>");
A("        <div style={s.heroGradient} />");
A("        <div style={s.heroContent}>");
A("          <div style={s.heroChip}>");
A("            <span style={s.heroChipDot} />");
A("            {businessInfo.city}{businessInfo.state ? ', ' + businessInfo.state : ''}");
A("            {businessInfo.serviceArea ? ' · Serving ' + businessInfo.serviceArea : ''}");
A("          </div>");
A("          <h1 style={s.heroH1}>");
A("            {(() => {");
A("              if (!generatedCopy.headline) return businessInfo.businessName;");
A("              const words = generatedCopy.headline.split(' ');");
A("              const last  = words.pop();");
A("              return (");
A("                <>");
A("                  {words.join(' ')}{words.length > 0 ? ' ' : ''}");
A("                  <span style={s.heroAccent}>{last}</span>");
A("                </>");
A("              );");
A("            })()} ");
A("          </h1>");
A("          <p style={s.heroSub}>{generatedCopy.subheadline}</p>");
A("          <div style={s.heroActions}>");
A("            <button style={s.btnBlue}>{generatedCopy.ctaPrimary || 'Get a Free Quote'}</button>");
A("            <button style={s.btnGhost}>");
A("              {generatedCopy.ctaSecondary || 'Explore Services'}");
A("              <svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" aria-hidden=\"true\">");
A("                <path d=\"M3 8h10M9 4l4 4-4 4\" stroke=\"currentColor\" strokeWidth=\"1.5\" strokeLinecap=\"round\" strokeLinejoin=\"round\"/>");
A("              </svg>");
A("            </button>");
A("          </div>");
A("        </div>");
A("      </section>");
A("");
A("      {/* STATS */}");
A("      <div style={s.statsBar}>");
A("        {stats.map((st, i) => (");
A("          <div key={i} style={s.stat}>");
A("            <span style={s.statNum}>{st.num}</span>");
A("            <span style={s.statLabel}>{st.label}</span>");
A("          </div>");
A("        ))}");
A("      </div>");
A("");
A("      {/* SERVICES BENTO */}");
A("      <section style={s.sectionWhite}>");
A("        <div style={s.servicesIntro}>");
A("          <span style={s.eyebrow}>Services</span>");
A("          <h2 style={s.sectionTitle}>");
A("            Everything your vehicle needs,{' '}");
A("            <em style={s.titleItalicBlue}>nothing it doesn&#8217;t.</em>");
A("          </h2>");
A("          <p style={{ ...s.bodyText, margin: '0 auto', textAlign: 'center' }}>");
A("            {(generatedCopy.servicesSection && generatedCopy.servicesSection.intro)");
A("              ? generatedCopy.servicesSection.intro");
A("              : 'From a single-car detail to a full fleet program, every service is executed to an exacting standard.'}");
A("          </p>");
A("        </div>");
A("        <div style={s.servicesBento}>");
A("          {services.map((svc, i) => {");
A("            const featured = i === 0;");
A("            return (");
A("              <div key={i} style={featured ? s.tileFeatured : s.tileBase}>");
A("                <div style={featured ? s.tileGlowFeatured : s.tileGlow} />");
A("                {featured && <div style={s.tileBadge}>Most Popular</div>}");
A("                <div style={featured ? s.tileIconFeatured : s.tileIcon}>");
A("                  {tileIcons[i % tileIcons.length]}");
A("                </div>");
A("                <h3 style={featured ? s.tileH3Featured : s.tileH3}>{svc.name}</h3>");
A("                <p style={featured ? s.tilePFeatured : s.tileP}>{svc.description}</p>");
A("                {businessInfo.priceRange && i === 0 && (");
A("                  <div style={{ marginTop: '24px', fontSize: '13px', fontWeight: 500, color: 'rgba(255,255,255,0.5)' }}>");
A("                    {businessInfo.priceRange}");
A("                  </div>");
A("                )}");
A("              </div>");
A("            );");
A("          })}");
A("        </div>");
A("      </section>");
A("");
A("      {/* BRANDS */}");
A("      <div style={s.brands}>");
A("        <span style={s.brandsEyebrow}>Trusted Professional Products</span>");
A("        <div style={s.brandsRow}>");
A("          {brandItems.map((br, i) => <span key={i} style={s.brand}>{br}</span>)}");
A("        </div>");
A("      </div>");
A("");
A("      {/* SPECIALIZATIONS */}");
A("      <div style={s.specStrip}>");
A("        <div>");
A("          <span style={s.eyebrow}>Specializations</span>");
A("          <h2 style={s.sectionTitle}>");
A("            Built for <em style={s.titleItalicBlue}>scale.</em>");
A("            <br />Trusted by industry.");
A("          </h2>");
A("          <p style={s.bodyText}>{generatedCopy.aboutText}</p>");
A("          <div style={s.specPillsGrid}>");
A("            {[");
A("              { label: 'Experience', val: (businessInfo.yearsInBusiness || '8') + '+ Years' },");
A("              { label: 'Response',   val: 'Same-day quotes' },");
A("              { label: 'Coverage',   val: businessInfo.city || 'Local Area' },");
A("              { label: 'Mobile',     val: 'On-site available' },");
A("            ].map((pill, i) => (");
A("              <div key={i} style={s.specPill}>");
A("                <div style={s.specPillLabel}>{pill.label}</div>");
A("                <div style={s.specPillVal}>{pill.val}</div>");
A("              </div>");
A("            ))}");
A("          </div>");
A("        </div>");
A("        <div>");
A("          {specialtyItems.slice(0, 3).map((sp, i) => (");
A("            <div key={i} style={s.fleetCard}>");
A("              <div style={s.fleetCardLine} />");
A("              <div style={s.fleetCardNum}>0{i + 1}</div>");
A("              <h3 style={s.fleetCardH3}>{typeof sp === 'object' ? sp.name : sp}</h3>");
A("              <p style={s.fleetCardP}>");
A("                {typeof sp === 'object'");
A("                  ? sp.description");
A("                  : 'Professional ' + String(sp).toLowerCase() + ' services tailored to your specific needs and operational requirements.'}");
A("              </p>");
A("              {Array.isArray(businessInfo.packages) && businessInfo.packages[i] && (");
A("                <div style={s.fleetTags}>");
A("                  <span style={s.tag}>{businessInfo.packages[i]}</span>");
A("                </div>");
A("              )}");
A("            </div>");
A("          ))}");
A("        </div>");
A("      </div>");
A("");
A("      {/* TESTIMONIALS */}");
A("      <section style={s.sectionOff}>");
A("        <div style={{ maxWidth: '520px', margin: '0 auto 72px', textAlign: 'center' }}>");
A("          <span style={s.eyebrow}>Reviews</span>");
A("          <h2 style={s.sectionTitle}>");
A("            What our clients <em style={s.titleItalicBlue}>say.</em>");
A("          </h2>");
A("        </div>");
A("        <div style={s.testiGrid}>");
A("          {testimonials.map((t, i) => {");
A("            const initials = t.name");
A("              ? t.name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase()");
A("              : String(i + 1);");
A("            return (");
A("              <div key={i} style={s.tcard}>");
A("                <div style={s.tcardStars}>&#9733;&#9733;&#9733;&#9733;&#9733;</div>");
A("                <p style={s.tcardP}>&ldquo;{t.text}&rdquo;</p>");
A("                <div style={s.tcardAuthor}>");
A("                  <div style={s.tcardAv}>{initials}</div>");
A("                  <div>");
A("                    <div style={s.tcardName}>{t.name}</div>");
A("                    {t.role && <div style={s.tcardRole}>{t.role}</div>}");
A("                  </div>");
A("                </div>");
A("              </div>");
A("            );");
A("          })}");
A("        </div>");
A("      </section>");
A("");
A("      {/* CONTACT */}");
A("      <section style={s.sectionWhite}>");
A("        <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: isMobile ? '48px' : '100px', alignItems: 'start' }}>");
A("          <div>");
A("            <span style={s.eyebrow}>Contact</span>");
A("            <h2 style={{ ...s.sectionTitle, marginBottom: '16px' }}>");
A("              Let&#8217;s get your vehicle <em style={s.titleItalicBlue}>sorted.</em>");
A("            </h2>");
A("            <p style={{ ...s.bodyText, marginBottom: '48px' }}>");
A("              Whether you need a single detail or a custom fleet contract &#8212; reach out and we&#8217;ll respond within 2 business hours.");
A("            </p>");
A("            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>");
A("              {[");
A("                { icon: '📞', label: 'Phone',    val: businessInfo.phone },");
A("                { icon: '📍', label: 'Location', val: businessInfo.address || [businessInfo.city, businessInfo.state].filter(Boolean).join(', ') },");
A("                { icon: '🕐', label: 'Hours',    val: businessInfo.hours },");
A("              ].filter(item => item.val).map((item, i) => (");
A("                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '14px', padding: '16px 20px', background: off, border: '1px solid ' + border, borderRadius: radiusSm }}>");
A("                  <div style={{ width: '38px', height: '38px', borderRadius: '10px', background: white, border: '1px solid ' + border, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '16px', flexShrink: 0, boxShadow: shadowSm }}>{item.icon}</div>");
A("                  <div>");
A("                    <div style={{ fontSize: '11px', color: text4, fontWeight: 500, letterSpacing: '0.3px' }}>{item.label}</div>");
A("                    <div style={{ fontSize: '14px', fontWeight: 500, color: text, marginTop: '1px' }}>{item.val}</div>");
A("                  </div>");
A("                </div>");
A("              ))}");
A("            </div>");
A("          </div>");
A("          <div style={{ background: off, border: '1px solid ' + border, borderRadius: radius, padding: '44px' }}>");
A("            <h3 style={{ fontSize: '20px', fontWeight: 500, color: text, letterSpacing: '-0.3px', marginBottom: '20px' }}>");
A("              Why Choose {businessInfo.businessName}?");
A("            </h3>");
A("            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>");
A("              {[");
A("                businessInfo.awards ? 'Award-winning: ' + businessInfo.awards : null,");
A("                businessInfo.yearsInBusiness ? businessInfo.yearsInBusiness + '+ years of professional experience' : null,");
A("                '100% satisfaction guarantee on every job',");
A("                'Professional-grade products — no shortcuts',");
A("                Array.isArray(businessInfo.packages) && businessInfo.packages.length");
A("                  ? 'Packages available: ' + businessInfo.packages.slice(0, 3).join(', ')");
A("                  : null,");
A("              ].filter(Boolean).map((item, i) => (");
A("                <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>");
A("                  <div style={{ width: '20px', height: '20px', borderRadius: '50%', background: blue + '15', border: '1px solid ' + blue + '30', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: '1px' }}>");
A("                    <svg width=\"10\" height=\"10\" viewBox=\"0 0 10 10\" fill=\"none\" aria-hidden=\"true\">");
A("                      <path d=\"M1.5 5l2.5 2.5 4.5-4.5\" stroke={blue} strokeWidth=\"1.5\" strokeLinecap=\"round\" strokeLinejoin=\"round\"/>");
A("                    </svg>");
A("                  </div>");
A("                  <span style={{ fontSize: '14px', color: text2, lineHeight: 1.5 }}>{item}</span>");
A("                </div>");
A("              ))}");
A("            </div>");
A("            <button style={{ width: '100%', background: blue, color: white, border: 'none', borderRadius: '10px', padding: '14px', fontFamily: dmSans, fontSize: '15px', fontWeight: 500, cursor: 'pointer', marginTop: '28px', boxShadow: '0 4px 16px ' + blue + '40', letterSpacing: '-0.2px' }}>");
A("              {generatedCopy.ctaPrimary || 'Get a Free Quote'}");
A("            </button>");
A("          </div>");
A("        </div>");
A("      </section>");
A("");
A("      {/* FOOTER */}");
A("      <footer style={s.footer}>");
A("        <div style={s.footerTop}>");
A("          <div>");
A("            <div style={s.footerBrandLogo}>");
A("              <div style={s.footerLogoRing}>");
A("                <div style={{ ...s.logoRingInner, borderColor: 'rgba(255,255,255,0.4)' }} />");
A("              </div>");
A("              {businessInfo.businessName}");
A("            </div>");
A("            <p style={s.footerBrandP}>{generatedCopy.footerTagline}</p>");
A("          </div>");
A("          <div>");
A("            <h4 style={s.footerColH4}>Services</h4>");
A("            {services.slice(0, 5).map((svc, i) => (");
A("              <a key={i} href=\"#services\" style={s.footerColLink}>{svc.name}</a>");
A("            ))}");
A("          </div>");
A("          <div>");
A("            <h4 style={s.footerColH4}>Get In Touch</h4>");
A("            {businessInfo.phone && (");
A("              <a href={'tel:' + businessInfo.phone.replace(/D/g, '')} style={s.footerColLink}>{businessInfo.phone}</a>");
A("            )}");
A("            {businessInfo.instagram && (");
A("              <a href={'https://instagram.com/' + businessInfo.instagram} style={s.footerColLink}>Instagram</a>");
A("            )}");
A("            {businessInfo.facebook && (");
A("              <a href={'https://facebook.com/' + businessInfo.facebook} style={s.footerColLink}>Facebook</a>");
A("            )}");
A("            {businessInfo.city && (");
A("              <span style={{ ...s.footerColLink, cursor: 'default' }}>");
A("                {businessInfo.city}{businessInfo.state ? ', ' + businessInfo.state : ''}");
A("              </span>");
A("            )}");
A("          </div>");
A("        </div>");
A("        <div style={s.footerBottom}>");
A("          <p style={{ fontSize: '12px' }}>");
A("            &copy; {new Date().getFullYear()} {businessInfo.businessName}. All rights reserved.");
A("          </p>");
A("          <div style={s.footerLoc}>");
A("            <div style={s.footerDot} />");
A("            {businessInfo.city}{businessInfo.state ? ', ' + businessInfo.state : ''}");
A("            {businessInfo.serviceArea ? ' · ' + businessInfo.serviceArea : ''}");
A("          </div>");
A("        </div>");
A("      </footer>");
A("");
A("    </div>");
A("  );");
A("}");
fs.writeFileSync(process.argv[2], c.join(NL), "utf8");
console.log("DONE", c.length, "lines written to", process.argv[2]);
